---
role_name_check: 1
platforms:
  - name: suryphp-instance
    box: debian/bookworm64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 2
verifier:
  name: testinfra
  directory: ../../tests
  options:
    v: true
