---
role_name_check: 1
driver:
  name: ec2
platforms:
  - name: suryphp_instance
    image: ${AMI_ID}
    instance_type: t2.micro
    region: ${AWS_REGION}
    vpc_id: ${VPC_ID}
    vpc_subnet_id: ${VPC_SUBNET_ID}
    private_key_path: ${SSH_PRIVATE_KEY_PATH}
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ../../tests
  options:
    v: true
